kind: pipeline
name: default

steps:
  - name: run-api-starter-tests
    image: node:10.16.0
    commands:
      - ./bin/run.sh
    when:
      status:
        - failure
        - success
      event:
        - pull_request
      branch:
        - master
        - "*:master"

services:
  - name: mongo
    image: mongo:4.0.10
    ports:
      - 27017
  - name: redis
    image: redis:5.0.5
    ports:
      - 6379
