version: '3.6'
services:
  mongo:
    command: mongod
    image: mongo:4.0.10
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootPassword
    networks:
      - ship
    ports:
      - "27017:27017"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  redis:
    image: redis:5.0.5
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    networks:
      - ship
    ports:
      - "6379:6379"
  api:
    build:
      context: "./"
      dockerfile: Dockerfile.dev
    networks:
      - ship
    environment:
      APP_ENV: development
    volumes:
      - "./src:/app/src"
    ports:
      - "3001:3001"
      - "8082:8082"
    depends_on:
      - "mongo"
      - redis
  migrator:
    command: npm run migrate
    build:
      context: "./"
      dockerfile: Dockerfile.dev
    networks:
      - ship
    volumes:
      - "./src:/app/src"
    depends_on:
      - mongo
  scheduler:
    command: npm run schedule-dev
    build:
      context: "./"
      dockerfile: Dockerfile.dev
    networks:
      - ship
    volumes:
      - "./src:/app/src"
    depends_on:
      - mongo
networks:
  ship:
    name: ship_network
