version: '3.6'
services:
  mongo:
    command: mongod
    image: mongo:4.0.10
    networks:
      - ship
    ports:
      - "27017:27017"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  redis:
    image: redis:5.0.5
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    networks:
      - ship
    ports:
      - "6379:6379"

networks:
  ship:
    name: ship_network
